services:
  service_a:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: service_a
    env_file:
      - ../.env
    networks:
      - lab3-net

networks:
  lab3-net:
    external: true
